# Generated by Django 6.0.2 on 2026-04-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('INTL', 'International LAN'), ('REG', 'Regional LAN'), ('ONL', 'Online'), ('MAJ', 'Major')], default='ONL', max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prize_pool', models.CharField(max_length=100)),
                ('team_count', models.IntegerField(default=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events_logo')),
                ('event_country', models.CharField(max_length=100)),
                ('event_country_flag', models.ImageField(blank=True, null=True, upload_to='events/flag')),
                ('event_city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
                'ordering': ['start_date'],
            },
        ),
    ]
