# Generated by Django 6.0.2 on 2026-04-18 09:08

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country_flag',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
