# Generated by Django 6.0.2 on 2026-04-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_city',
        ),
    ]
