# Generated by Django 6.0.2 on 2026-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_team_remove_player_age_remove_player_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
