# Generated by Django 6.0.2 on 2026-03-19 16:25

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='flag',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_flag',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
