# Generated by Django 6.0.2 on 2026-03-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_flag_team_team_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
